[workspace]
members = [
  "crates/lib/akari_common",
  "crates/lib/akari_core",
  "crates/lib/akari_utils",
  "crates/lib/akari_const",
  "crates/lib/akari_integrators",
  "crates/lib/akari_adjit",
  "crates/lib/akari",
  "crates/lib/akari_gpu",
  "crates/lib/akari_net",
  "crates/bin/akari_cli",
  "crates/bin/akari_import",
  "crates/bin/akari_verify",
]

[profile.dev]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
lto = true