[workspace]
members = [
  "crates/lib/akari_common",
  "crates/lib/akari_core",
  "crates/lib/akari_utils",
  "crates/lib/akari_const",
  "crates/lib/akari_integrators",
  "crates/lib/akari",
  "crates/lib/akari_gpu",
  "crates/bin/akari_cli",
  "crates/bin/akari_import",
  "crates/bin/akari_verify",
]
